# backend/scripts/run_lexicon_check.py
"""
Standalone check: run the ambiguity lexicon against a list of ACs,
with no dependency on Jira, Claude, or the rest of the pipeline.

Usage:
    python -m backend.scripts.run_lexicon_check
"""

from backend.pipeline.module1.ambiguity_penalty import compute_ambiguity_penalty

# Paste in the ACs from your held-out validation sample here
acs = [
    "Users can register using a manual registration form with the following fields: — Name: Required. Error if empty: \"Name is required\".",
    "Users can register using a manual registration form with the following fields: — Email: Required. Must be a valid email format. Error if invalid: \"Invalid email number\".",
    "Users can register using a manual registration form with the following fields: — Password: Required. Masked input. Error if empty: \"Password is required\".",
    "Users can register using a manual registration form with the following fields: — Confirm Password: Required. Masked input. Error if empty: \"Confirm the password\".",
    "Users can register using a manual registration form with the following fields: — Create Account Button: Validates all fields and creates the account. On success, redirects to the Home Screen.",
    "Users can register quickly using their existing Google identity: — Sign up with Google Button: Initiates the Google OAuth 2.0 flow when tapped.",
    "There is a path for users who already have an account to prevent duplicate registrations: — Log in Link: Text \"Log in\" located at the bottom of the form.",
    "If the email is already registered, display the message: \"An account with this email already exists\".",
    "Branding & Subscribe Section: — Displays \"Exclusive\" as the footer logo/title.",
    "Branding & Subscribe Section: — Displays \"Subscribe\" heading with sub-text \"Get 10% off your first order\".",
    "Branding & Subscribe Section: — Email Input Field: Text input with placeholder \"Enter your email\".",
    "Branding & Subscribe Section: — Submit (➤) Icon Button: Positioned inside/adjacent to the input field. — On valid email + submit: subscribes the user and shows a success confirmation message.",
    "Branding & Subscribe Section: — Submit (➤) Icon Button: Positioned inside/adjacent to the input field. — On invalid/empty email + submit: displays an inline validation error (e.g., \"Please enter a valid email\").",
    "Support Column: — Displays heading \"Support\".",
    "Support Column: — Shows static company address (e.g., \"111 Bijoy sarani, Dhaka, DH 1515, Bangladesh.\").",
    "Support Column: — Shows support email (e.g., \"exclusive@gmail.com\") as a clickable mailto: link.",
    "Support Column: — Shows support phone number (e.g., \"+88015-88888-9999\") as a clickable tel: link.",
    "Account Column: — Displays heading \"Account\".",
    "Account Column: — Contains navigational links: My Account, Login / Register, Cart, Wishlist, Shop.",
    "Account Column: — Each link navigates to its respective page.",
    "Account Column: — Login / Register link routes to Login page if the user is a guest, or is replaced/redirected appropriately if the user is already authenticated.",
    "Quick Link Column: — Displays heading \"Quick Link\".",
    "Quick Link Column: — Contains navigational links: Privacy Policy, Terms Of Use, FAQ, Contact.",
    "Quick Link Column: — Each link navigates to its respective static/informational page.",
    "Quick Link Column: — Download App Column: — Displays heading \"Download App\".",
    "Quick Link Column: — Download App Column: — Shows promotional text \"Save $3 with App New User Only\".",
    "Quick Link Column: — Download App Column: — Displays a QR code image that links to the app download page.",
    "Quick Link Column: — Download App Column: — Displays \"Google Play\" badge button linking to the Play Store listing.",
    "Quick Link Column: — Download App Column: — Displays \"App Store\" badge button linking to the Apple App Store listing.",
    "Quick Link Column: — Download App Column: — Displays social media icon links: Facebook, Twitter, Instagram, LinkedIn — each opens the respective social profile in a new tab.",
    "Copyright Bar: — Displays \"© Copyright Rimel 2022. All right reserved\" centered at the bottom of the footer, separated by a divider line.",
    "Other information — The Footer is a global component rendered on all pages (Home, Shop, Cart, Wishlist, Checkout, etc.).",
    "Other information — Footer content (address, email, phone, social links, copyright text) is sourced from a central configuration/CMS so it can be updated without code changes.",
    "Other information — Footer must be responsive: columns stack vertically on smaller screen widths.",
    "Other information — All external links (App Store, Google Play, social icons) open in a new tab (target=\"_blank\").",
    "Book Management Page (Screen 1): — Displays heading \"Book Management\".",
    "Book Management Page (Screen 1): — Displays \"Add Book\" button (+ icon), aligned top-right. — On click: opens the Add Book popup (Screen 2).",
    "Book Management Page (Screen 1): — Displays a \"Search by ID or Type\" input field with a search icon, next to the Add Book button. — On entering a value: filters the table by matching ID or Type.",
    "Book Management Page (Screen 1): — Displays a \"Search by ID or Type\" input field with a search icon, next to the Add Book button. — If no match is found, displays a \"No books found\" message.",
    "Book Management Page (Screen 1): — Displays a table with column headers: ID, Name, Type, Language, Availability, Action. — Each row represents one book copy in the inventory.",
    "Book Management Page (Screen 1): — Displays a table with column headers: ID, Name, Type, Language, Availability, Action. — Availability shows \"Available\" or \"Borrowed\".",
    "Book Management Page (Screen 1): — Displays a table with column headers: ID, Name, Type, Language, Availability, Action. — Action column displays three icons: edit (pencil), delete (trash), and view (document). — Edit icon click: opens the Update Book popup (Screen 3), pre-filled with that book's current data.",
    "Book Management Page (Screen 1): — Displays a table with column headers: ID, Name, Type, Language, Availability, Action. — Action column displays three icons: edit (pencil), delete (trash), and view (document). — Delete icon click: opens the Delete Confirmation popup (Screen 5).",
    "Book Management Page (Screen 1): — Displays a table with column headers: ID, Name, Type, Language, Availability, Action. — Action column displays three icons: edit (pencil), delete (trash), and view (document). — View icon click: opens the View Book popup (Screen 4).",
    "Book Management Page (Screen 1): — Standard header (admin name/role, date/time, settings icon) and sidebar (Dashboard, Catalog, Books, Users, Branches, Log Out) are rendered as on the Admin Dashboard, with \"Books\" highlighted as the active section.",
    "Add Book Popup (Screen 2): — Displays heading \"Add Book\" with a book icon, and a close (×) icon top-right.",
    "Add Book Popup (Screen 2): — Name Field: Required text input, placeholder \"Name\".",
    "Add Book Popup (Screen 2): — Language Field: Required text input, placeholder \"Language\".",
    "Add Book Popup (Screen 2): — Type Field: Required text input, placeholder \"Type\".",
    "Add Book Popup (Screen 2): — Quantity Field: Required numeric input, placeholder \"Quantity\".",
    "Add Book Popup (Screen 2): — \"CANCEL\" button: closes the popup without saving, discarding entered data.",
    "Add Book Popup (Screen 2): — \"ADD\" button: — On valid submission: creates new book record(s) in the inventory (creating \"Quantity\" number of copies), closes the popup, refreshes the table, and shows a success confirmation.",
    "Add Book Popup (Screen 2): — \"ADD\" button: — On empty/invalid required field(s): displays inline validation errors.",
    "Update Book Popup (Screen 3): — Displays heading \"Update Book\" with a book icon, and a close (×) icon top-right.",
    "Update Book Popup (Screen 3): — Name, Language, Type, and Quantity fields, pre-filled with the selected book's current values.",
    "Update Book Popup (Screen 3): — \"CANCEL\" button: closes the popup without saving changes.",
    "Update Book Popup (Screen 3): — \"UPDATE\" button: — On valid submission: saves the changes to that book record, closes the popup, refreshes the table, and shows a success confirmation.",
    "Update Book Popup (Screen 3): — \"UPDATE\" button: — On empty/invalid required field(s): displays inline validation errors.",
    "View Book Popup (Screen 4): — Displays heading \"View Book\" with a book icon, and a close (×) icon top-right.",
    "View Book Popup (Screen 4): — Displays read-only fields: \"Book ID\", \"Name\", \"Type\", \"Language\".",
    "View Book Popup (Screen 4): — Displays a \"Saved by\" panel showing the name and role of the admin who created/last saved the record (e.g., \"Nisal Gunasekara (Admin)\").",
    "View Book Popup (Screen 4): — Displays a \"CLOSE\" button. — On click: closes the popup and returns to the Book Management table.",
    "Delete Confirmation Popup (Screen 5): — Displays heading \"Delete Confirmation\" with a trash icon, and a close (×) icon top-right.",
    "Delete Confirmation Popup (Screen 5): — Displays confirmation text: \"Are you certain you wish to proceed with the deletion of the selected entry?\".",
    "Delete Confirmation Popup (Screen 5): — Displays \"CONFIRM\" button. — On click: permanently deletes the selected book record, closes the popup, refreshes the table, and shows a success confirmation (e.g., toast \"Book deleted successfully\").",
    "Delete Confirmation Popup (Screen 5): — Closing the popup via the (×) icon (without confirming) cancels the deletion and returns to the table unchanged.",
    "Admin Sign In Screen: — Displays heading \"Welcome Back !!\" with sub-text \"Please enter your credentials to log in\".",
    "Admin Sign In Screen: — Email Field: Required text input, placeholder \"Email\".",
    "Admin Sign In Screen: — Password Field: Required text input (masked), placeholder \"Password\".",
    "Admin Sign In Screen: — \"Forgot password?\" link, positioned below the Password field. — On click: navigates to the Forgot Password screen.",
    "Admin Sign In Screen: — \"SIGN IN\" button. — On valid admin credentials: authenticates the user and redirects to the Admin Dashboard.",
    "Admin Sign In Screen: — \"SIGN IN\" button. — On invalid credentials: displays an inline error message (e.g., \"Invalid email or password\") without navigating away.",
    "Admin Sign In Screen: — \"SIGN IN\" button. — On valid credentials belonging to a non-admin (regular User) account: redirects to the User Dashboard instead, or displays an access-restriction message — confirm exact behavior with the team, since this Sign In screen appears shared/identical to the regular User Sign In screen.",
    "Admin Sign In Screen: — \"SIGN IN\" button. — On empty required field(s): displays inline validation errors under the respective field(s).",
    "Admin Sign In Screen: — Branding panel displays \"BookWorm Library\" logo.",
    "Forgot Password Screen: — Displays \"BACK\" button, top-right, returning to the Admin Sign In screen.",
    "Forgot Password Screen: — Displays heading \"Forgot Password\" with sub-text \"Please enter your username\".",
    "Forgot Password Screen: — Email Field: Required text input, placeholder \"Email\".",
    "Forgot Password Screen: — \"RESET PASSWORD\" button. — On valid/existing admin email: triggers an OTP to be sent to the admin's registered email and navigates to the OTP Verification screen.",
    "Forgot Password Screen: — \"RESET PASSWORD\" button. — On unrecognized email: displays an inline error message (e.g., \"No account found with this email\").",
    "Forgot Password Screen: — \"RESET PASSWORD\" button. — On empty field: displays inline validation error.",
    "Forgot Password Screen: — Branding panel displays \"BookWorm Library\" logo and tagline \"Your premier digital library for borrowing and reading books\".",
    "OTP Verification Screen (\"Check your Mailbox\"): — Displays \"BACK\" button, top-left, returning to the Forgot Password screen.",
    "OTP Verification Screen (\"Check your Mailbox\"): — Displays heading \"Check your Mailbox\" with sub-text \"Please enter the OTP to proceed\".",
    "OTP Verification Screen (\"Check your Mailbox\"): — OTP Field: Required text input, placeholder \"OTP\".",
    "OTP Verification Screen (\"Check your Mailbox\"): — \"VERIFY\" button. — On correct OTP: navigates to the Reset Password screen.",
    "OTP Verification Screen (\"Check your Mailbox\"): — \"VERIFY\" button. — On incorrect OTP: displays an inline error message (e.g., \"Invalid OTP, please try again\").",
    "OTP Verification Screen (\"Check your Mailbox\"): — \"VERIFY\" button. — On expired OTP: displays an inline error message and offers a \"Resend OTP\" option (not shown in current design — flag for clarification).",
    "OTP Verification Screen (\"Check your Mailbox\"): — \"VERIFY\" button. — OTP validity duration is 10mins.",
    "OTP Verification Screen (\"Check your Mailbox\"): — Branding panel (right side, reversed layout) displays \"BookWorm Library\" logo and tagline \"Your premier digital library for borrowing and reading books\".",
    "Reset Password Screen: — Displays \"BACK\" button, top-right, returning to the OTP Verification screen (or Sign In — confirm with team).",
    "Reset Password Screen: — Displays heading \"Reset Password\" with sub-text \"Please enter your new password\".",
    "Reset Password Screen: — New Password Field: Required text input (masked), placeholder \"New Password\"; must meet password strength rules (to be defined).",
    "Reset Password Screen: — Confirm Password Field: Required text input (masked), placeholder \"Confirm Password\"; must match New Password.",
    "Reset Password Screen: — \"RESET PASSWORD\" button. — On matching, valid passwords: updates the admin account password, shows a success confirmation, and redirects to the Admin Sign In screen.",
    "Reset Password Screen: — \"RESET PASSWORD\" button. — On mismatched passwords: displays an inline error (e.g., \"Passwords do not match\").",
    "Reset Password Screen: — \"RESET PASSWORD\" button. — On weak password (not meeting strength rules): displays an inline error describing the requirement.",
    "Reset Password Screen: — Branding panel displays \"BookWorm Library\" logo and tagline \"Your premier digital library for borrowing and reading books\"."
]

score, details = compute_ambiguity_penalty(acs)

print(f"Ambiguity score: {score:.4f}")
print(f"Total words: {details['total_words']}")
print(f"Matched terms ({details['ambiguous_count']}):")
for m in details["matched_terms"]:
    print(f"  - '{m['term']}'  [{m['category']}]")